classes:
  2-4: 0
  3-4: 1
  4-4: 2
  barline: 3
  dot: 4
  eighth: 5
  fa_clef: 6
  half: 7
  quarter: 8
  rest: 9
  rest_eighth: 10
  rest_quarter: 11
  rest_sixteenth: 12
  sixteenth: 13
  sol_clef: 14
  whole: 15


beats_to_note:
  4: "whole"
  2: "half"
  1: "quarter"
  0.5: "eighth"
  0.25: "sixteenth"


note_to_beats:
  whole: 4.0
  half: 2.0
  quarter: 1.0
  eighth: 0.5
  sixteenth: 0.25
  rest_whole: 4
  rest_half: 2
  rest_quarter: 1
  rest_eighth: 0.5
  rest_sixteenth: 0.25


note_to_pitch:
  C2 : 36
  C#2 : 37
  D2 : 38
  D#2 : 39
  E2 : 40
  F2 : 41
  F#2 : 42
  G2 : 43
  G#2 : 44
  A2 : 45
  A#2 : 46
  B2 : 47
  C3 : 48
  C#3 : 49
  D3 : 50
  D#3 : 51
  E3 : 52
  F3 : 53
  F#3 : 54
  G3 : 55
  G#3 : 56
  A3 : 57
  A#3 : 58
  B3 : 59
  C4 : 60
  C#4 : 61
  D4 : 62
  D#4 : 63
  E4 : 64
  F4 : 65
  F#4 : 66
  G4 : 67
  G#4 : 68
  A4 : 69
  A#4 : 70
  B4 : 71
  C5 : 72
  C#5 : 73
  D5 : 74
  D#5 : 75
  E5 : 76
  F5 : 77
  F#5 : 78
  G5 : 79
  G#5 : 80
  A5 : 81
  A#5 : 82
  B5 : 83
  C6 : 84
  C#6 : 85
  D6 : 86
  D#6 : 87
  E6 : 88
  F6 : 89
  F#6 : 90
  G6 : 91
  G#6" : 92
  A6 : 93
  A#6 : 94
  B6 : 95


model_path: "algorithm/ML/model.pt"


helper_functions:
  model_image_input_size: [224, 224]
  model_input_size: [1, 224, 224]
  model_config: [1, 64, 7, 2, 3]


